Add support for simple log outputs as alternative to email
cronie-crond/cronie pull request #147
Opened 2023-04-26 11:08 UTC by JohnnyJayJay

This PR adds support for a new environment variable `INHERIT_OUTPUTS` which, when set, indicates that the outputs (stdout and stderr) of a job should not be sent by mail and instead just be written to stdout/stderr as usual. The value of this feature is that it allows for a more uniform logging approach without a mail server set up. 

For example, on my system, `anacron` is run by `cronie` every hour (as is the default). The outputs of cronie and  anacron are logged in `journalctl`. It would be nice to have the logs of my anacron jobs there as well, which can be achieved by leaving stdout and stderr of the job processes as-is.

This PR's motivation is similar to that of #135 but completely ignores the mail functionality.

2023-04-26 11:30 UTC, DerTev commented
lgtm

2023-04-26 16:29 UTC, t8m requested changes
Final nits

2023-04-26 17:29 UTC, JohnnyJayJay commented
Just to be clear, since some of the annotations refer to code that was not written by me: do you want me to reformat the whole anacron project for consistency? I find the style questionable, but intentionally decided against touching it and left it as-is. This concerns indentation, curly braces and new lines.

2023-04-26 17:36 UTC, t8m commented
> Just to be clear, since some of the annotations refer to code that was not written by me: do you want me to reformat the whole anacron project for consistency? I find the style questionable, but intentionally decided against touching it and left it as-is. This concerns indentation, curly braces and new lines.

No, do not reformat please. Just change the lines I've commented about.

2023-04-27 09:34 UTC, JohnnyJayJay commented on anacron/runjob.c
> +    if (!jr->no_mail_output && file_size(jr->output_fd) > jr->mail_header_size) mail_output = 1;
I simplified this more since the if-else is not needed there.

2023-04-27 11:57 UTC, t8m approved these changes

2023-04-27 12:01 UTC, merged

2023-04-27 12:01 UTC, t8m commented
Merged. Thank you for your contribution.