Address issues found by coverity scan
cronie-crond/cronie pull request #88
Opened 2021-04-29 15:17 UTC by khardix

These issues were found by running several static checkers on the codebase (see [cronie-1.5.7-coverity-imp.err.txt](https://github.com/cronie-crond/cronie/files/6399748/cronie-1.5.7-coverity-imp.err.txt) for the original report).

2021-04-29 15:26 UTC, t8m requested changes

2021-04-29 15:26 UTC, t8m commented on src/database.c
> +			strncpy(fname, dp->d_name, NAME_MAX); fname[NAME_MAX] = '\0';
Please put this on a separate line.

2021-04-30 10:04 UTC, khardix commented on src/database.c
> +			strncpy(fname, dp->d_name, NAME_MAX); fname[NAME_MAX] = '\0';
Line split.

2021-04-30 10:06 UTC, t8m approved these changes

2021-04-30 10:06 UTC, merged

2021-04-30 10:08 UTC, t8m commented
Merged. Thank you.